### ISSUE TITLE
Movies

### ISSUE THREAD

**Issue by Zero0Q** [XBMCSpot/docshadrach.repository#1]
Are you going to add all movies from dl.my-film.org to the addon or is it only for new movies?

**Comment by XBMCSpot** [comment]
It's just for new movies for now.

**Comment by Zero0Q** [comment]
That's ok Thanks for the great addon..

**Comment by Zero0Q** [comment]
Can you help me with default.py file, i'm trying to edit the file to get all listings instead of only new ones? 
Is it OK with you if i do that and if you could point me in right direction. Thank You

**Comment by XBMCSpot** [comment]
There is a part that is missing here, don't come with the addon, that part retrieves all the data from page and makes the output. The addon just update that output file. If you know some python you can make this looking in the updater part of the addon.
To edit to get all movies you have to look that they now are filtering by year, and filtering by IMDb rating as well.
Anyway, until now I'm just showing only 2016/2017 releases with more than 7 points of rating, but in the new version I will show more movies, from 2010 until 2017.
So, you have to look to remove those filters and make an entire output file if you want to show all the movies. I can't do it for you, I'm out of time..

**Comment by Zero0Q** [comment]
Thank you for answer. I just started to learn about python. I tried to remove the filter but with no luck here. Anyway thanks for help..

**Comment by XBMCSpot** [comment]
You're welcome.
